# generated by Riccardo with:
# rail(base) ricc-macbookpro3:pasta ricc$ rails g migration add_most_appropriate_pasta_id_to_sauce most_appropriate_pasta_id:integer
class AddMostAppropriatePastaIdToSauce < ActiveRecord::Migration[7.0]
  def change
    add_column :sauces, :most_appropriate_pasta_id, :integer
  end
end
